---
- hosts: localhost
  become: true
  tasks:
     - name: golang download
       get_url: 
           url: https://redirector.gvt1.com/edgedl/go/go1.9.2.linux-amd64.tar.gz
           dest: /tmp/go1.9.2.linux-amd64.tar.gz
     - name: golang install
       shell: tar -C /usr/local -xzf /tmp/go1.9.2.linux-amd64.tar.gz
