---
- hosts: localhost
  become: true
  tasks:
     - name: Update apt-cache 
       apt: update_cache=yes

     - name: Add software-properties-common
       apt: name=software-properties-common state=latest
    
     - name: Add ppa:ansible/ansible
       apt_repository: repo=ppa:ansible/ansible   

     - name: Update apt-cache 
       apt: update_cache=yes

     - name: Install Ansible
       apt: name=ansible state=latest

     - name: Install Vim
       apt: name=vim state=latest

     - name: Install jq
       apt: name=jq state=latest

     - name: install finger
       apt: name=finger state=latest

     - name: install pip
       apt: name=python-pip state=latest

     - pip: name=docker-py

     - name: create admin group
       group: name=admin state=present

     - name: install emv
       user: name=emv uid=1001 groups=admin,docker shell=/bin/bash

     - name: make emv ssh dir
       file: dest=/home/emv/.ssh mode=700 owner=emv group=admin state=directory

     - name: make emv ssh authorizedkeys
       file: dest=/home/emv/.ssh/authorized_keys mode=600 owner=emv group=admin state=file

     - name: get metadata
       get_url: 
         url: https://metadata.packet.net/metadata
         dest: /tmp/packet.metadata

     - name: write keys
       shell: jq -r '.ssh_keys[]' /tmp/packet.metadata > /home/emv/.ssh/authorized_keys

     - name: emv sudoer create
       file: dest=/etc/sudoers.d/emv.sudo state=touch mode=440

     - name: emv sudoer copy
       copy: content="emv ALL=(ALL) NOPASSWD:ALL\n" dest=/etc/sudoers.d/emv

     - name: quiet cloud warnings
       file: dest=/var/lib/cloud/instance/warnings/.skip state=touch

